version: '3.9'

services:
  redis:
    restart: unless-stopped
    image: redis:latest
    container_name: redis_container
    ports:
      - "6380:6379"

  postgres:
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root99173asd67"
      POSTGRES_DB: "teeth"
    volumes:
      - ./data/psql_data:/var/lib/postgresql/data/
    ports:
      - "5411:5432"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=root99173asd67
    volumes:
      - ./data/minio_data:/data
    command: server /data

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8999:8080

