version: '3'

tasks:
  runHttpServer:
    cmds:
      - go run ./cmd/api/main.go

  runGrpcServer:
    cmds:
      - go run ./cmd/auth/main.go

  createMigration:
    cmds:
      - migrate create -ext sql -dir ./migrations -seq {{.TITLE}}

  migrateMigration:
    cmds: 
      - migrate -database "postgres://{{.LOGIN}}:{{.PASSWORD}}@127.0.0.1:5411/teeth?sslmode=disable" -path ./migrations {{.ACTION}} 

  forceMigration:
    cmds:
      - migrate -database "postgres://{{.LOGIN}}:{{.PASSWORD}}@127.0.0.1:5411/teeth?sslmode=disable" -path ./migrations force {{.VERSION}}
      