basePath: /
definitions:
  sendResponse.Response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
  service.AuthorizationBody:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  service.AuthorizationResponse:
    properties:
      accessToken:
        type: string
    type: object
  service.GetAuthorByIdResponse:
    properties:
      avatarId:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  service.RegistrationBody:
    properties:
      isAdmin:
        type: boolean
      login:
        type: string
      password:
        type: string
    type: object
  service.SaveAuthorBody:
    properties:
      description:
        type: string
      login:
        type: string
      name:
        type: string
    type: object
  service.UpdateTokensBody:
    properties:
      login:
        type: string
    type: object
  service.UpdateTokensResponse:
    properties:
      accessToken:
        type: string
    type: object
host: localhost:8585
info:
  contact: {}
  description: API Server for TeethPortal Application
  title: Teeth Portal API
  version: "1.0"
paths:
  /api/arts:
    post:
      consumes:
      - application/json
      parameters:
      - collectionFormat: csv
        description: New files
        in: formData
        items:
          type: file
        name: file
        required: true
        type: array
      - in: formData
        name: authorId
        type: integer
      - in: formData
        name: content
        type: string
      - in: formData
        name: description
        type: string
      - in: formData
        name: title
        type: string
      - in: formData
        name: type
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/sendResponse.Response'
      summary: Create new art
      tags:
      - arts
  /api/auth/authorization:
    post:
      consumes:
      - application/json
      parameters:
      - description: user information
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/service.AuthorizationBody'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/service.AuthorizationResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/sendResponse.Response'
      summary: Authorization user
      tags:
      - auth
  /api/auth/registration:
    post:
      consumes:
      - application/json
      parameters:
      - description: User information
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/service.RegistrationBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/sendResponse.Response'
      summary: Registration user
      tags:
      - auth
  /api/auth/tokens:
    post:
      consumes:
      - application/json
      parameters:
      - description: Access token
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/service.UpdateTokensBody'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/service.UpdateTokensResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/sendResponse.Response'
      summary: Update user JWT - tokens
      tags:
      - auth
  /api/authors:
    post:
      consumes:
      - application/json
      parameters:
      - description: New file
        in: formData
        name: file
        required: true
        type: file
      - in: formData
        name: description
        type: string
      - in: formData
        name: login
        type: string
      - in: formData
        name: name
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/sendResponse.Response'
      summary: Create new author
      tags:
      - authors
  /api/authors/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/service.GetAuthorByIdResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/sendResponse.Response'
      summary: Get all authors
      tags:
      - authors
  /api/authors/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/sendResponse.Response'
      summary: Delete author
      tags:
      - authors
    get:
      consumes:
      - application/json
      parameters:
      - description: Author ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.GetAuthorByIdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/sendResponse.Response'
      summary: Get author by id
      tags:
      - authors
    put:
      consumes:
      - application/json
      parameters:
      - description: Author id
        in: path
        name: id
        required: true
        type: integer
      - description: New author information
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/service.SaveAuthorBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/sendResponse.Response'
      summary: Update data for author
      tags:
      - authors
  /api/authors/{id}/avatar/{fileName}:
    get:
      consumes:
      - application/json
      parameters:
      - description: File name
        in: path
        name: fileName
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/sendResponse.Response'
      summary: Get author's avatar by file name
      tags:
      - authors
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: Author id
        in: path
        name: id
        required: true
        type: integer
      - description: File name
        in: path
        name: fileName
        required: true
        type: string
      - description: New file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/sendResponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/sendResponse.Response'
      summary: Update author avatar
      tags:
      - authors
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
